services:
  - type: web
    name: codigo-azul-backend
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install --include=dev && npm run build && cd ..
    startCommand: npm start
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_VERSION
        value: "20.18.0"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: CORS_ORIGIN
        value: "*"
      - key: DB_HOST
        value: aws-0-sa-east-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.qiofdrrnizzopzhwklfi
      - key: DB_PASSWORD
        value: Tesobnemcp123
      - key: JWT_SECRET
        value: super_secret_jwt_key_codigo_azul_2026
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: FCM_PROJECT_ID
        value: proyecto---olimpiada-2026
      - key: FCM_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@proyecto---olimpiada-2026.iam.gserviceaccount.com
      - key: FCM_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCtrhTyb2caZO+Z\noM3e+UpuJMKNOpsCYz6cqzvB/5ZhRnFH2d+KTF54HSRKsb/ecpFHyr6EuJz+4s46\nxCFvApl2SDGcxDhlsCAHb7yMaxdr0t+XjjSYZ0w/wJYfFBCXeDYtb+392w1l9g6U\nbZnOV/SXOmtly8no882GZmysZLmYeNjv7pUByjwLNQGGZQ4gmwwYV0bjV+9BVNvi\n2fHtHpOQ+jLzOUpFmm/W35H0WOXMW60HCbI6qlvcq61lDmAu/vgRhwWvoZ+Q1gd0\n6HKTlmI9UfjxvDV5hGgMnBHH48RINWY71XhSPKvCzVo6m812NH6OX3Xwa6vlVvgy\n0z2kSC7fAgMBAAECggEAD++4yVQSjFf1qk2YhlyuiTPDTE0z2wC7Ronpxk/K/ysF\nCvhBbEG8q13VLitoNSOjFAjU+X2tHjA2hyrm/HYrGbDfKIjSufXywmvsy5+p+wFS\n9eedCNz1oKXtwHVJXnSv1/R8zH3UmWX+CX2TDt2AOn4oS6Nq5/6y/aGZWCo343cQ\nkHaxTIX20aBH8ADbO0Cq7nSlS2+fbFA29oEoqekHmaQHEKErDSvRDPY6d7kn8nz0\nMOaLkFTaRSDDX/aIVuc5nZojk7Kfr6T/Ugk2tnoDWB8+4JQg/Z/PF/bKwgdP3ZL0\nfl+8uAOAhBV0JqKiKg0WdErtAwdCpbP5ijTcSINTaQKBgQDXNI1q72oaPSNBzyj2\nRXZwTUA+iDBLDVOoqWwW9p01CA4KCLl52yt676RuzYP0qV2vx2Opa/16Y3t4MY7k\nq/lABiFPEaAiKA1HusvPZPlkdfkgqbFhmVKVp5iVgty0AyNWPargmkDBwqg0EERU\ne7puVcLPL+P4GreC/eOgbB6X6QKBgQDOmmXANciFx2Gm155hHaoPeXT/SPWVhNdG\n/TqM3RqEgDYYwPCu4HIODQAzb+ZC0vaNkfMGfhInDmtLy/LAZOwGztnGdeU/wVhX\njfxWOiPtZ4mWqndGJYIvuDkoaaK1C5YSZ8ZgeOfnjJEDgkfxVvj8+/QZrJL0b9tH\n51VhWUybhwKBgQCx+J3zD2eZp3He3KktcSiPmvNEQ3BcwPqsguAG5ZAA6VZi6fAp\nXB1LH5/GmmNEFESMN8Ktu8b2TgsvzRw09Bu+3NLzBsp9NM42wb4HF6Q/dmi+oFc3\nNYrchKtlCcHnhKjWi00jTa28D3T3CXTYwTHeSUJAAYTwC3gz9i8m3gM28QKBgQCx\nm1NLaDDoqF0PQ57Yl9rBEMV+TCcqkRdL5Jc3zz9jlqBqqTp+613BLHX2wgRtf9QK\nIeSMuUY7ow6kC0C1Gk05EQtvq5wXMcwTAHFjYvnNtcs25XZBrC79fN5OGnmQL9Sk\nH+gOuQGLMXDcVlwoYX8MZEAU7iEq1xnn9zuTw2Oy8wKBgG4Xi+0aIkhaJQW3zy8+\nbzrKbbZ7BtvixaJx0ezr/wTXeQlVGt6WsUYZORECo/ANAmJu4j2HovoCv8cfezpw\nfOPHVYtBpKP8kLC2AnfDsbuXDK9XoPYiy+JLoJTk0r3elQHuTd+UzpMhNuBCp9fF\nPYigOIA75jN2jKu5WgtM+uj2\n-----END PRIVATE KEY-----\n"
